### ISSUE TITLE
gtfs2lc in macOS

### ISSUE THREAD

**Issue by dachafra** [linkedconnections/gtfs2lc#33]
I'm trying to run gtfs2lc in a macOS but some problems appear:

- When I run gtfs2lc-sort it seems like the command remove all "r" from the files and change their format, an example: https://github.com/dachafra/spaingtfs/tree/master/gtfs2lc/metro. The output doesn't say anything about an error:
`dchaves$ gtfs2lc-sort metro/`
`Converting newlines dos2unix`
`Removing UTF-8 artifacts in directory metro/`
`Sorting files in directory metro/`
- After that, if I run gtfs2lc and the output is:
`dchaves$ gtfs2lc metro/`
`GTFS to linked connections converter use --help to discover more functions`

The same dataset in an Ubuntu dist works perfectly.

**Comment by pietercolpaert** [comment]
I guess removing the dos2unix from the command gtfs2lc-sort.sh script should work fine?

**Comment by dachafra** [comment]
Removing the dos2unix the script works fine
