### ISSUE TITLE
Crash when a trip isn't in trips.txt

### ISSUE THREAD

**Issue by Bertware** [linkedconnections/gtfs2lc#74]
When trying to convert the attached GTFS file, GTFS2LC crashes
```

3|datasets | Indexing services and routes succesful!
3|datasets | Error: Unhandled "error" event. (Did not find this trip id in trips.txt: 55408414)
3|datasets |     at ConnectionsBuilder.emit (events.js:186:19)
3|datasets |     at ConnectionsBuilder.onerror (_stream_readable.js:663:12)
3|datasets |     at emitOne (events.js:116:13)
3|datasets |     at ConnectionsBuilder.emit (events.js:211:7)
3|datasets |     at onwriteError (_stream_writable.js:417:12)
3|datasets |     at onwrite (_stream_writable.js:439:5)
3|datasets |     at ConnectionsBuilder.afterTransform (_stream_transform.js:90:3)
3|datasets |     at _expandTrip.then.catch (/var/www/dk.lc.bertmarcelis.be/node_modules/gtfs2lc/lib/ConnectionsBuilder.js:79:5)
3|datasets |     at <anonymous>
3|datasets |     at process._tickCallback (internal/process/next_tick.js:189:7)

```
[DSB.zip](https://github.com/linkedconnections/gtfs2lc/files/2604905/DSB.zip)

My guess: FeedValidator makes no problem of unused trips. Only trips which are in trips.txt should be used, not all trips in stop_times.txt.

Removing references to this trip from stop_times resolves the issue.

**Comment by pietercolpaert** [comment]
What version of gtfs2lc do you use? This looks like a bug that has been fixed before as part of this PR: https://github.com/linkedconnections/gtfs2lc/pull/70#issuecomment-436557737

**Comment by pietercolpaert** [comment]
Although I think your problem is different: is your `stop_times.txt` mentioning a trip that doesn’t exist in trips.txt? Then I think that’s a problem in your GTFS feed, no?

**Comment by Bertware** [comment]
Looks like a mistake in a GTFS splitting script on my side, as Google spec confirms that the first column should always resolve: https://support.google.com/transitpartners/answer/7168579?hl=en&ref_topic=7171045

My bad, sorry!
